#Indicates the style of the configuration
style: iosxr

ordering:

- lineage:
  - startswith: tacacs server
  order: 100
- lineage:
  - startswith: aaa group server
  - re_search: server name
  order: 200
- lineage:
  - startswith: aaa group server
  - re_search: no server-private
  order: 300
- lineage:
  - startswith: aaa
  order: 400
- lineage:
  - startswith: no aaa
  order: 500
- lineage:
  - startswith: ip
  order: 600
- lineage:
  - startswith: no ip
  order: 700
#- lineage:
#  - startswith: transport preferred none
#  order: 800
#- lineage:
#  - startswith: transport preferred ssh
#  order: 900
  #- startswith: no neighbor

#if there is a delta, overwrite these parents instead of one of their children
sectional_overwrite: []
#- lineage:
#  - re_search: ^((ip|ipv4|ipv6) )?access-list

sectional_overwrite_no_negate:
- lineage:
  - startswith: aaa accounting system default start-stop
#- lineage:
#  - startswith: interface
- lineage:
  - startswith: prefix-set
- lineage:
  - startswith: route-policy
- lineage:
  - startswith: extcommunity-set
- lineage:
  - startswith: community-set

parent_allows_duplicate_child: []
#- lineage:
#  - startswith: route-policy

sectional_exiting:
- lineage:
  - startswith: router bgp
  - startswith: address-family
  exit_text: exit-address-family

#adds +1 indent to lines following start_expression and removes the +1 indent for lines following end_expression
indent_adjust: []
#- start_expression: ^\s*template
#  end_expression: ^\s*end-template

#substitions against the full multi-line config text
full_text_sub: []
#- search: 'banner\s(exec|motd)\s(\S)\n(.*\n){1,}(\2)'
#  replace: ''

#substitions against each line of the config text
per_line_sub: []
#- search: ^interface
#  replace: ''
#- search: ^Building configuration.*
#  replace: ''
#- search: ^Current configuration.*
#  replace: ''
#- search: ^! Last configuration change.*
#  replace: ''
#- search: ^! NVRAM config last updated.*
#  replace: ''
#- search: ^ntp clock-period .*
#  replace: ''
#- search: ^version.*
#  replace: ''
#- search: ^ logging event link-status$
#  replace: ''
#- search: ^ logging event subif-link-status$
#  replace: ''
#- search: ^\s*ipv6 unreachables disable$
#  replace: ''
#- search: ^end$
#  replace: ''
#- search: '^\s*[#!].*'
#  replace: ''
#- search: ^ no ip address
#  replace: ''
#- search: ^ exit-peer-policy
#  replace: ''
#- search: ^ exit-peer-session
#  replace: ''
#- search: ^ exit-address-family
#  replace: ''
#- search: ^crypto key generate rsa general-keys.*$
#  replace: ''
#- search: ^no\s+aaa\s+new-model
#  replace: ''

idempotent_commands_blacklist: []
#- lineage:
#  - lineage expression

#These commands do not require negation, they simply overwrite themselves
idempotent_commands:
- lineage:
  - startswith: aaa accounting system default
  
- lineage:
  - startswith: transport preferred
#  - startswith: aaa accounting
#  - startswith: aaa authorization
#  - startswith: aaa authentication
  #- endswith: peer-group
- lineage:
  - startswith: line 
  - re_search: transport 

  
- lineage:
  - startswith: router bgp
  - re_search: neighbor (\d+\.\d+\.\d+\.\d+) peer-group
#- lineage:
#  - startswith: interface
#  - startswith: ipv4 address

- lineage:
  - startswith: aaa group server

#Default when expression: list of lineage expressions
negation_default_when: []
#- lineage:
#  - lineage expression

#Negate substitutions: lineage expression -> negate with
negation_negate_with: []
#- lineage:
 # - re_search: transport preferred telnet
 # use: transport preferred none
